# Generated by Django 4.2.10 on 2024-02-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_alter_album_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Pop Music', 'Genre Pop'), ('Jazz Music', 'Genre Jazz'), ('Rock Music', 'Genre Rock'), ('Country Music', 'Genre Country'), ('Dance Music', 'Genre Dance'), ('R&B Music', 'Genre Rnb'), ('Hip Hop Music', 'Genre Hip Hop'), ('Other', 'Genre Other')], max_length=30),
        ),
    ]
