# Generated by Django 4.2.9 on 2024-02-24 11:43

import django.core.validators
from django.db import migrations, models
import world_of_speed.profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(3), world_of_speed.profiles.models.validate_username], verbose_name='Username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('age', models.IntegerField(help_text='Age requirement: 21 years and above.', validators=[django.core.validators.MinValueValidator(21)], verbose_name='Age')),
                ('password', models.CharField(max_length=20, verbose_name='Password')),
                ('first_name', models.CharField(blank=True, max_length=25, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=25, verbose_name='Last Name')),
                ('profile_picture', models.URLField(blank=True, verbose_name='Profile Picture')),
            ],
        ),
    ]
